package com.gilrossi.despesas.financialassistant;

public enum FinancialAssistantIntent {
	PERIOD_SUMMARY,
	TOTAL_BY_CATEGORY_IN_PERIOD,
	TOP_EXPENSES_IN_PERIOD,
	MONTH_OVER_MONTH_CHANGE,
	SAVINGS_RECOMMENDATIONS,
	RECURRING_EXPENSES,
	HIGHEST_SPENDING_CATEGORY,
	INCREASE_ALERTS,
	UNKNOWN
}
