#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"

# shellcheck source=/dev/null
source "${script_dir}/load-governed-env.sh" prod

: "${BACKEND_IMAGE:=ghcr.io/example/despesas-backend:main}"
: "${DB_NAME:=despesasdb}"
: "${DB_USERNAME:=postgres}"
: "${DB_PASSWORD:=CHANGE_ME}"
: "${DB_URL:=jdbc:postgresql://postgres:5432/despesasdb}"
: "${APP_PUBLIC_HOST:=app.example.com}"
: "${N8N_PUBLIC_HOST:=n8n.example.com}"
: "${APP_SECURITY_TOKEN_SECRET:=CHANGE_ME}"
: "${APP_SECURITY_PASSWORD_RESET_SECRET:=CHANGE_ME}"
: "${APP_SECURITY_CORS_ALLOWED_ORIGIN_PATTERNS:=https://${APP_PUBLIC_HOST}}"
: "${APP_OPERATIONAL_EMAIL_INGESTION_KEY_ID:=preflight-key}"
: "${APP_OPERATIONAL_EMAIL_INGESTION_SECRET:=preflight-secret}"
: "${APP_OPERATIONAL_EMAIL_INGESTION_PREVIOUS_KEY_ID:=}"
: "${APP_OPERATIONAL_EMAIL_INGESTION_PREVIOUS_SECRET:=}"
: "${APP_OPERATIONAL_EMAIL_INGESTION_MAX_CLOCK_SKEW_SECONDS:=300}"
: "${APP_OPERATIONAL_EMAIL_INGESTION_NONCE_TTL_SECONDS:=86400}"
: "${APP_FRONTEND_WEB_DIST:=file:/app/frontend-web/}"
: "${TZ:=America/Sao_Paulo}"
: "${GENERIC_TIMEZONE:=America/Sao_Paulo}"
: "${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:=true}"
: "${N8N_ENCRYPTION_KEY:=CHANGE_ME}"
: "${N8N_HOST:=${N8N_PUBLIC_HOST}}"
: "${N8N_PROTOCOL:=https}"
: "${N8N_PORT:=5678}"
: "${WEBHOOK_URL:=https://${N8N_PUBLIC_HOST}/}"
: "${N8N_PROXY_HOPS:=1}"
: "${N8N_BLOCK_ENV_ACCESS_IN_NODE:=false}"
: "${DESPESAS_BACKEND_BASE_URL:=http://backend:8080}"
: "${DESPESAS_OPERATIONAL_EMAIL_INGESTION_KEY_ID:=preflight-key}"
: "${DESPESAS_OPERATIONAL_EMAIL_INGESTION_SECRET:=preflight-secret}"
: "${DESPESAS_OUTLOOK_SOURCE_ACCOUNT:=owner.outlook@example.com}"
: "${DESPESAS_SMOKE_OUTLOOK_TO:=owner.outlook@example.com}"
: "${GOOGLE_GEMINI_MODEL:=gemini-2.5-flash}"
: "${TRAEFIK_ENTRYPOINTS:=websecure}"
: "${TRAEFIK_CERTRESOLVER:=letsencrypt}"
export BACKEND_IMAGE DB_NAME DB_USERNAME DB_PASSWORD DB_URL
export APP_PUBLIC_HOST N8N_PUBLIC_HOST APP_SECURITY_TOKEN_SECRET APP_SECURITY_PASSWORD_RESET_SECRET
export APP_SECURITY_CORS_ALLOWED_ORIGIN_PATTERNS
export APP_OPERATIONAL_EMAIL_INGESTION_KEY_ID APP_OPERATIONAL_EMAIL_INGESTION_SECRET
export APP_OPERATIONAL_EMAIL_INGESTION_PREVIOUS_KEY_ID APP_OPERATIONAL_EMAIL_INGESTION_PREVIOUS_SECRET
export APP_OPERATIONAL_EMAIL_INGESTION_MAX_CLOCK_SKEW_SECONDS APP_OPERATIONAL_EMAIL_INGESTION_NONCE_TTL_SECONDS
export APP_FRONTEND_WEB_DIST TZ GENERIC_TIMEZONE N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS N8N_ENCRYPTION_KEY
export N8N_HOST N8N_PROTOCOL N8N_PORT WEBHOOK_URL N8N_PROXY_HOPS N8N_BLOCK_ENV_ACCESS_IN_NODE
export DESPESAS_BACKEND_BASE_URL DESPESAS_OPERATIONAL_EMAIL_INGESTION_KEY_ID
export DESPESAS_OPERATIONAL_EMAIL_INGESTION_SECRET DESPESAS_OUTLOOK_SOURCE_ACCOUNT DESPESAS_SMOKE_OUTLOOK_TO
export GOOGLE_GEMINI_MODEL TRAEFIK_ENTRYPOINTS TRAEFIK_CERTRESOLVER

cd "${repo_root}"
docker compose \
  -f deploy/compose.base.yml \
  -f deploy/compose.prod.yml \
  config >/tmp/despesas-production-compose.rendered.yml

echo "Compose de producao validado em /tmp/despesas-production-compose.rendered.yml"
