package com.gilrossi.despesas.emailingestion;

public enum EmailIngestionDecisionReason {
	IMPORTED,
	MANUALLY_IMPORTED,
	REVIEW_REQUESTED,
	MANUALLY_REJECTED,
	IRRELEVANT_CLASSIFICATION,
	DESIRED_IGNORE,
	LOW_CONFIDENCE,
	DUPLICATE_MESSAGE_ID,
	DUPLICATE_FINGERPRINT,
	UNSUPPORTED_CURRENCY,
	MISSING_TOTAL_AMOUNT,
	ITEM_TOTAL_MISMATCH,
	CATEGORY_NOT_FOUND,
	SUBCATEGORY_NOT_FOUND,
	SUBCATEGORY_REQUIRED
}
