create table space_references (
    id bigint generated by default as identity primary key,
    household_id bigint not null references households (id) on delete restrict,
    type varchar(40) not null,
    name varchar(120) not null,
    normalized_name varchar(120) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create index idx_space_references_household_type_name
    on space_references (household_id, type, lower(name));

create index idx_space_references_household_normalized_name
    on space_references (household_id, normalized_name);

create unique index uq_space_references_household_type_normalized_active
    on space_references (household_id, type, normalized_name)
    where deleted_at is null;
