alter table space_references
    add constraint uq_space_references_id_household unique (id, household_id);

create table incomes (
    id bigint generated by default as identity primary key,
    household_id bigint not null references households (id) on delete restrict,
    description varchar(140) not null,
    amount numeric(15, 2) not null,
    received_on date not null,
    space_reference_id bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_incomes_space_reference_household
        foreign key (space_reference_id, household_id)
        references space_references (id, household_id)
        on delete restrict
);

create index idx_incomes_household_received_on_id
    on incomes (household_id, received_on desc, id desc);

create index idx_incomes_household_space_reference_received_on
    on incomes (household_id, space_reference_id, received_on desc, id desc);
