create table tb_despesas (
    id bigint generated by default as identity primary key,
    descricao varchar(100) not null,
    valor numeric(15, 2) not null check (valor > 0),
    data date not null,
    categoria varchar(50) not null
);

create index idx_tb_despesas_data_id on tb_despesas (data, id);
