create table fixed_bills (
    id bigint generated by default as identity primary key,
    household_id bigint not null references households (id) on delete restrict,
    description varchar(140) not null,
    amount numeric(15, 2) not null,
    first_due_date date not null,
    frequency varchar(20) not null,
    context varchar(40) not null,
    category_id bigint not null,
    category_name_snapshot varchar(80) not null,
    subcategory_id bigint not null,
    subcategory_name_snapshot varchar(80) not null,
    space_reference_id bigint,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_fixed_bills_amount_positive check (amount > 0),
    constraint chk_fixed_bills_frequency check (frequency in ('MONTHLY')),
    constraint chk_fixed_bills_context check (context in ('CASA', 'VEICULO', 'UBER', 'PJ', 'BUSCA_EMPREGO', 'PETS', 'GERAL')),
    constraint fk_fixed_bills_category_household
        foreign key (category_id, household_id)
        references categories (id, household_id)
        on delete restrict,
    constraint fk_fixed_bills_subcategory_household_category
        foreign key (subcategory_id, household_id, category_id)
        references subcategories (id, household_id, category_id)
        on delete restrict,
    constraint fk_fixed_bills_space_reference_household
        foreign key (space_reference_id, household_id)
        references space_references (id, household_id)
        on delete restrict
);

create index idx_fixed_bills_household_active_due_date_id
    on fixed_bills (household_id, active, first_due_date desc, id desc);

create index idx_fixed_bills_household_space_reference_due_date
    on fixed_bills (household_id, space_reference_id, first_due_date desc, id desc);
