create table households (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create table users (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    email varchar(160) not null,
    password_hash varchar(255) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create unique index uq_users_lower_email_active on users (lower(email))
    where deleted_at is null;

create table household_members (
    id bigint generated by default as identity primary key,
    household_id bigint not null references households (id) on delete restrict,
    user_id bigint not null references users (id) on delete restrict,
    role varchar(20) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz,
    constraint chk_household_members_role check (role in ('OWNER', 'MEMBER'))
);

create unique index uq_household_members_household_user_active
    on household_members (household_id, user_id)
    where deleted_at is null;

create table categories (
    id bigint generated by default as identity primary key,
    household_id bigint not null references households (id) on delete restrict,
    name varchar(80) not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create index idx_categories_household_id_name on categories (household_id, lower(name));

create unique index uq_categories_household_name_active
    on categories (household_id, lower(name))
    where deleted_at is null and active = true;

create table subcategories (
    id bigint generated by default as identity primary key,
    category_id bigint not null references categories (id) on delete restrict,
    name varchar(80) not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create index idx_subcategories_category_id_name on subcategories (category_id, lower(name));

create unique index uq_subcategories_category_name_active
    on subcategories (category_id, lower(name))
    where deleted_at is null and active = true;

insert into households (id, name) values (1, 'Casa Principal');
insert into users (id, name, email, password_hash) values (1, 'Sistema', 'system@local.invalid', '{noop}');
insert into household_members (id, household_id, user_id, role) values (1, 1, 1, 'OWNER');

select setval('households_id_seq', (select max(id) from households), true);
select setval('users_id_seq', (select max(id) from users), true);
select setval('household_members_id_seq', (select max(id) from household_members), true);
