create table expenses (
    id bigint generated by default as identity primary key,
    household_id bigint not null references households (id) on delete restrict,
    description varchar(140) not null,
    amount numeric(15, 2) not null,
    due_date date not null,
    context varchar(40) not null,
    category varchar(80) not null,
    subcategory varchar(80) not null,
    notes varchar(255),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz,
    constraint chk_expenses_amount_positive check (amount > 0),
    constraint chk_expenses_context check (context in ('CASA', 'VEICULO', 'UBER', 'PJ', 'BUSCA_EMPREGO', 'PETS', 'GERAL'))
);

create index idx_expenses_household_id_due_date_id on expenses (household_id, due_date desc, id desc);
create index idx_expenses_household_id_category_id_due_date_id on expenses (household_id, category, due_date desc, id desc);

create table payments (
    id bigint generated by default as identity primary key,
    expense_id bigint not null references expenses (id) on delete restrict,
    amount numeric(15, 2) not null,
    paid_at date not null,
    method varchar(20) not null,
    notes varchar(255),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz,
    constraint chk_payments_amount_positive check (amount > 0),
    constraint chk_payments_method check (method in ('PIX', 'DINHEIRO', 'DEBITO', 'CREDITO', 'TRANSFERENCIA', 'BOLETO'))
);

create index idx_payments_expense_id_paid_at_id on payments (expense_id, paid_at desc, id desc);
